version: '3'

services:
  app:
    build:
      context: ./
      dockerfile: ./.docker/dockerfiles/app.dockerfile
    volumes:
      - ./:/var/www
      - ./.docker/config/supervisor:/etc/supervisor.d
    env_file:
      - .env
    depends_on:
      - mariadb
    networks:
      - default
    ports:
      - 9000
  webserver:
    build:
      context: ./
      dockerfile: ./.docker/dockerfiles/webserver.dockerfile
    working_dir: /var/www
    volumes:
      - ./:/var/www
    environment:
      VIRTUAL_HOST: $VIRTUAL_HOST
    networks:
      - default
      - proxy
    ports:
      - 80
    depends_on:
      - app
  mariadb:
    image: mariadb:10.4.2-bionic
    volumes: 
      - database:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    networks:
      - default
    ports:
      - $DB_PORT
volumes:
  database:
  public:

networks:
  proxy:
    external:
      name: $PROXY_NETWORK
